<?php 

    $stringConfiguration  = '<div%s>';
    $stringConfiguration .= '<button type="button" class="close" data-dismiss="alert" aria-hidden="true">';
    $stringConfiguration .= '&times;';
    $stringConfiguration .= '</button>';
    $stringConfiguration .= '<ul><li>';
    
    $flashMessenger->setMessageOpenFormat($stringConfiguration)
     ->setMessageSeparatorString('</li><li>')
     ->setMessageCloseString('</li></ul></div>');

    echo $flashMessenger->render(
        'info',   
        ['alert', 'alert-dismissible', 'alert-info']);
    echo $flashMessenger->render(
        'warning',   
        ['alert', 'alert-dismissible', 'alert-warning']);

    echo $flashMessenger->render(
        'error',   
        ['alert', 'alert-dismissible', 'alert-danger']);

    echo $flashMessenger->render(
        'success',   
        ['alert', 'alert-dismissible', 'alert-success']);
?>

